### ISSUE TITLE
variance estimation in  electron.cpp

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/stempy#105]
In electronthresholds.cpp there is a function called [`calculateVariance()`.](https://github.com/OpenChemistry/stempy/blob/4a84fb4903bfaf4b43211beb48428f294fd66e65/stempy/electronthresholds.cpp#L16) I believe this function is incorrect. It is written as:
v = values
n = number samples
mean = mean(values)
```
sigma = sum( v_i^2 )/(n-1) - mean^2
return sigma
```

It should be
```
sigma_squared = (1 / (n-1)) * sum( (v_i - mean)^2 )
sigma = sqrt(sigma_squared)
return sigma
```

**Comment by ercius** [comment]
Correction:
> It should be
sigma_squared = (1 / (n-1)) * sum( (v_i - mean)^2 )
sigma = sqrt(sigma_squared)
return sigma

The variance is equal to sigma^2. So [calculateVariance](https://github.com/OpenChemistry/stempy/blob/4a84fb4903bfaf4b43211beb48428f294fd66e65/stempy/electronthresholds.cpp#L16) should return sigma^2. Line 90 in `electronthresholds.cpp` is `auto stdDev = sqrt(variance);`

So function logic should be (in pseudo code):
```
variance = (1 / (n-1)) * sum( (v_i - mean)^2 )
return variance
```
Or really:
``` c++
double calculateVariance(std::vector<int16_t>& values, double mean)
{
  double v1 = 0;
  double sigma2;

  for (size_t i = 0; i < values.size(); i++) {
    v1 += pow(values[i] - mean, 2.0);
  }
  sigma2 = v1 / (values.size() - 1.0);
  return sigma2;
}
```

I tested this locally and got the correct variance and sigma for a real data set. However, the optimize algorithm reports the wrong value.
``` c++
 // optimize
  auto result = optAlgo.optimize(initialState);
```
Im not sure about the logic for creating the histogram and for input to the optimize algorithm. This needs to be looked at.

For a good example dataset:
See ncemhub/4Dcamera/2020.01.09/data_scan59.h5. The mean and variance should be  about 20.5 and 2.5. See this plot of the histogram of the values in the first 100 frames below. I clipped the max to 40 for clarity.
![Figure_1](https://user-images.githubusercontent.com/15657108/72223848-44f39700-3528-11ea-8e8b-b47c6431d5cf.png)

stempy.electron_count(verbose=True) gives these results for this dataset:
>****Statistics for calculating electron thresholds****
number of samples: 400
min sample: 10
max sample: 270
mean: 20.50597531165606
variance: 6.188895291213131
std dev: 2.4877490410435557
number of bins: 123
x-ray threshold n sigma: 10.0
background threshold n sigma: 4.0
background threshold: -35452.56137493795
xray threshold: 45.383465722091614

The background threshold is obviously incorrect. Not sure if this is just a reporting issue or the actual value used for the counting. The x-ray threshold seems to indicate the fitted sigma is 4.5 This is incorrect.

A potential issue is how the histogram is calculated. Gaussian fitting can over fit to tails and the central part of the Gaussian in this histogram is only about 6 bins wide (10 to 270 with 123 bins). I would suggest doing the histogram based on the initial sigma rather than min and max values. So a histogram from 0 to x*sigma where x is about 10 - 20 might be a good solution.

**Comment by cjh1** [comment]
I will take a look at this, I pretty sure the background threshold is not a reporting problem, when I ran it I got a different value, but running it again gave another large negative value, looks like an issue with the fitting. What should be the ball park values for background threshold and x-ray threshold?

**Comment by cjh1** [comment]
yep, looks like the optimizer is bailing before, we even get close to a fit.

**Comment by cjh1** [comment]
The optimizer we are using has had a few updates, I will move to the new version and find out why we are getting a good fit.

**Comment by ercius** [comment]
> What should be the ball park values for background threshold and x-ray threshold?

The background should be about 25 to 30 counts. The x-ray should probably be higher than 10 sigma, It likely can be ignored for now.

>The optimizer we are using has had a few updates, I will move to the new version and find out why we are getting a good fit.

Thanks for looking into it! Optimizing the histogram might also help with this fitting as well. The estimation of the variance will be biased to higher values due to the electron counts. I got an optimized gaussian sigma of about 2.0 whereas the estimation method gave 2.5.

**Comment by cjh1** [comment]
@ercius So I think I have resolved these issues. In the end I switch to Eigen's optimizer which seems to perform better ( as in it converges! ). I also added the optimized values to the verbose output for better debugging. Here is the output for scan59:

```
number of samples: 400
min sample: 10
max sample: 270
mean: 20.496885677384743
variance: 6.199037465091556
std dev: 2.489786630434736
number of bins: 123
x-ray threshold n sigma: 10.0
background threshold n sigma: 4.0
optimized mean: 20.406274975887907
optimized std dev: 2.0192670251123714
background threshold: 28.48334307633739
xray threshold: 45.3947519817321
```

I have pushed the changes to the branch we have been working on. I also fixed an out of memory issue. Note: That when I tried to optimize the histogram I seemed to get a "worst" fit, so that change has not been made ( I am assume we are looking for a sigma of ~2 for this scan ).

**Comment by cjh1** [comment]
@ercius Also thank you for all your help tracking down these issues!

**Comment by ercius** [comment]
@cjh1 Happy to help!

>Note: That when I tried to optimize the histogram I seemed to get a "worst" fit, so that change has not been made ( I am assume we are looking for a sigma of ~2 for this scan ).

Anything around 2.0 is correct for this sample. The value you report above (2.019) is very close to the value I got using scipy.optimize.curvefit() offline for this dataset.

I think there are still issues with this though. In some cases I still get a threshold value which is not correct. The verbose output is correctly reporting the values. It seems that the mean of the fit can be around zero. For example, I ran the counting on a 512x1024 scan with these results:

>****Statistics for calculating electron thresholds****
number of samples: 1200
min sample: 11
max sample: 257
mean: 20.594560597109698
variance: 5.168411482958311
std dev: 2.273414058845927
number of bins: 246
x-ray threshold n sigma: 50.0
background threshold n sigma: 4.0
background threshold: 9.593656235383708
xray threshold: 134.26526353940605

The background threshold does not match the returned std dev and the mean. It should be about 30. If you look at the code the background threshold is calculated as 
``` c++
auto backgroundThreshold =
result.state[1] + result.state[2] * backgroundThresholdNSigma;
```
However, the mean that is printed is not the optimized mean, but the estimated mean since this is the returned value:
``` c++ 
auto mean = calculateMean(samples);
...
ret.mean = mean;
...
return ret;
```

So, the printed and returned mean is actually the estimated mean and not the optimized mean. But the background_threshold is based on the optimized mean.

Lastly, I think the optimizer function needs to be initialized with the estimated mean and variance instead of what is actually happening:
```c++
  initialState[0] = static_cast<double>(histogram[indexOfMaxElement]);
  initialState[1] =
    (bins[indexOfMaxElement + 1] - bins[indexOfMaxElement]) / 2.0;
  initialState[2] = stdDev;

  // optimize
  auto result = optAlgo.optimize(initialState);
```

If Im reading this correctly, `initialState[1]` is the input mean which is just set to the middle of the histogram range. This should be set to the `mean` estimated earlier instead.
```c++
  initialState[0] = static_cast<double>(histogram[indexOfMaxElement]);
  initialState[1] = mean;
  initialState[2] = stdDev;

  // optimize
  auto result = optAlgo.optimize(initialState);
```

That is likely to improve the fitting and not cause it to produce bad fits in the future.

So, two things:
1. Fix the return of the mean value to the optimized value
2. Fix the initialization of the mean value

**Comment by cjh1** [comment]
@ercius For 1. The code is now print out the estimated mean and the optimized mean. See [here](https://github.com/OpenChemistry/stempy/blob/sector-reader/stempy/electronthresholds.cpp#L169-L178), may be I am misunderstand what you are saying? I will fix 2.

**Comment by cjh1** [comment]
I have pushed a change for 2.

**Comment by ercius** [comment]
> For 1. The code is now print out the estimated mean and the optimized mean. See here, may be I am misunderstand what you are saying?

This printout is good. Then you can see the estimated std dev and the optimized std dev.

> I have pushed a change for 2.

Great. Ill rebuild and see if that works better on the data Im using to test.

**Comment by cjh1** [comment]
I think the reason you are not seeing the optimized mean is you need to update the Python side as well. 'pip install -U -e .' in the repo directory should do it. The '-e' option symlinks the files so in the future, changes in the repo will be reflected in the Python environment.

**Comment by ercius** [comment]
Ah...that might be it. Ill use -e and then I can also test changes I make to the code more easily.

Eventually, Ill track that branch and can start doing pull requests :)

**Comment by cjh1** [comment]
Pull requests always welcome :-)

**Comment by cjh1** [comment]
I am also going to try a get that sector-reader branch merged by the end of the week.

**Comment by cjh1** [comment]
I have now merged that branch.

**Comment by ercius** [comment]
This is working correctly in the matter branch now. Closing.
